### ISSUE TITLE
undefined function or variable 'fexact'

### ISSUE THREAD

**Issue by ONeillMB1** [tamilieberman/IntrasamplePolymorphismCaller#1]
In trying to run the function pileup_to_diversity_matrix('sample.mpileup','sample.mat',4411532) I receive the following error:
"Undefined function or variable 'fexact'".

Is there a package or something that needs to be loaded?

**Comment by tamilieberman** [comment]
Hi Mary,

Yes, I'll add that file to the github. I hope there aren't more missing!

Tami

**Comment by tamilieberman** [comment]
Done!
